---
markdown: redcarpet

redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - smart

title: ixti's personal scratchpad

assets:
  compress:
    css: sass
    js:  uglifier
  cache_assets: true

zipballs:
  sources: _downloads
  dirname: downloads

tags:
  template: _layouts/archive

categories:
  template: _layouts/archive

archives:
  template: _layouts/archive

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
